on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  actions-job:
    runs-on: ubuntu-latest

    steps:
      - name: say hellow
        uses: actions/hello-world-javascript-action@v1
        with:
          name: Toka
  