on:
  workflow_dispatch:

jobs:
  hybrid-job:
    runs-on: ubuntu-latest
    steps:
      - name: run command in ubuntu VM
        run: echo "this runs in ubuntu VM"

      - name: run inside an Alpine container
        uses: docker://alpine:latest
        with:
          entrypoint: /bin/sh
          args: -c "echo this runs in Alpine container"

      - name: run another command in ubuntu VM
        run: echo "back to the ubuntu VM"